function OnTdConnect(sender,arg)

if arg.result == QuantBox.CSharp2CTP.ConnectionStatus.E_confirmed
    global td;
    % ÏÂµ¥
    td.SendOrder('IF1212',...
        QuantBox.CSharp2CTP.TThostFtdcDirectionType.Buy,...
        '0',...
        '1',...
        1,2250,...
        QuantBox.CSharp2CTP.TThostFtdcOrderPriceTypeType.LimitPrice,...
        QuantBox.CSharp2CTP.TThostFtdcTimeConditionType.GFD,...
        QuantBox.CSharp2CTP.TThostFtdcContingentConditionType.Immediately,...
        0);
end

end
